

-- Add doctor account
INSERT INTO DOCTOR (DR_ID, DR_NAME, DEPPT, SPLTY, CONTACT)
VALUES (22646525, 'MARI FRANZ ESPELITA', 'NEUROLOGY', 'NEUROLOGY', '09223344556');

INSERT INTO ACCOUNTS(USERTYPE, [PASSWORD], EMP_ID, USER_LNAME, USER_FNAME)
VALUES(1, 'doctorsample', 22646525, 'ESPELITA', 'MARI FRANZ');
